#!/usr/bin/perl
#
#
if ($#ARGV == -1) {
 print "Usage: $0 <output file> <ffa ps-files>\n";
 exit 0;
}

$out = $ARGV[0];
shift @ARGV;

foreach (@ARGV) {
 $dm = $_;
 $dm =~ s/^.*\.clip\.([\d\.]+)\.ffa.*$/$1/;
 $m{$dm} = $_;
}

$call_string = "psjoin ";
foreach $i (sort { $a <=> $b } keys %m) {
 $call_string = $call_string . "$m{$i}" . " ";
}
$call_string = $call_string . " > $out";
system ("$call_string");
